# frozen_string_literal: true

source "https://rubygems.org"

gem "rails", ">= 7.0.0"

group :active_record do
  platforms :jruby do
    gem "activerecord-jdbcmysql-adapter", ">= 1.2" if ENV["CI_DB_ADAPTER"] == "mysql2"
    gem "activerecord-jdbcpostgresql-adapter", ">= 1.2" if ENV["CI_DB_ADAPTER"] == "postgresql"
    gem "activerecord-jdbcsqlite3-adapter", ">= 1.2"
  end

  platforms :ruby, :mswin, :mingw do
    gem "mysql2", ">= 0.3.14" if ENV["CI_DB_ADAPTER"] == "mysql2"
    gem "pg", ">= 0.14" if ENV["CI_DB_ADAPTER"] == "postgresql"
    gem "sqlite3", ">= 1.3.0"
  end

  gem "paper_trail", ">= 12.0"
end

gem "image_processing", ">= 1.2"
gem "mlb", ">= 0.7"
gem "puma"
gem "rails_admin_next", path: "../../"
gem "ruby-vips", ">= 2.1"

group :development, :test do
  gem "importmap-rails", require: false
end
