# frozen_string_literal: true

source "https://rubygems.org"

gem "rails", ">= 7.0.0"

group :active_record do
  gem "mysql2" if ENV["CI_DB_ADAPTER"] == "mysql2"
  gem "paper_trail"
  gem "pg" if ENV["CI_DB_ADAPTER"] == "postgresql"
  gem "sqlite3"
end

gem "image_processing", ">= 1.2"
gem "mlb", ">= 0.7"
gem "puma"
gem "rails_admin_next", path: "../../"
gem "ruby-vips", ">= 2.1"

group :development, :test do
  gem "importmap-rails", require: false
end
